# Generated by Django 5.1.3 on 2025-09-14 20:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icon', models.CharField(default='🧠', max_length=10)),
                ('color', models.CharField(default='#6A1B9A', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('front_text', models.CharField(max_length=100)),
                ('front_image', models.ImageField(upload_to='flashcard_images/fronts/')),
                ('front_audio', models.FileField(blank=True, null=True, upload_to='flashcard_sounds/fronts/')),
                ('back_video', models.FileField(upload_to='flashcard_videos/backs/')),
                ('back_text', models.CharField(help_text='e.g., A is for Apple', max_length=200)),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='flashcards.deck')),
            ],
        ),
    ]
